### ISSUE TITLE
"using-gulp-with-jekyll" Post typo

### ISSUE THREAD

**Issue by remunizz** [AaronLasseigne/aaronlasseigne.github.com#10]
Hello,
i found a basic typo on the page: http://aaronlasseigne.com/2016/02/03/using-gulp-with-jekyll/
"Let’s break down the 'upper' task. It starts by getting all text files from the current _direcotry_ via gulp.src."

btw, the post is pretty good! congratulations (:

**Comment by AaronLasseigne** [comment]
I'm glad you enjoyed it.
